config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/max', to: 'data#max'
  get '/index', to: 'data#index'

  root 'data#index'
end

app/models/input_file.rb
module InputFile
  FILE_PATH = "#{Rails.root}/input.txt".freeze
  ATTRIBUTES = { username: 0, inbox: 2, size: 4 }

  def self.attributes
    ATTRIBUTES
  end

  def self.max(attribute)
    return [] if attribute.blank?
    where.max do |value, next_value|
      begin
        index = ATTRIBUTES[attribute.to_sym]
        value[index] <=> next_value[index]
      rescue StandardError => e
        raise_attribute_name
      end
    end
  end

  def self.where(hash = {})
    response = []
    file = File.open(FILE_PATH, 'r') do |f|
      f.each_line do |line|
        array_line = line.split(' ')
        response << array_line
        hash.each_pair do |k, v|
          next if v.blank?
          begin
            index = ATTRIBUTES[k]
            response.delete(array_line) if array_line[index] != v
          rescue StandardError => e
            raise_attribute_name
          end
        end
      end
    end
    response
  end

  private

  def self.raise_attribute_name
    raise "Invalid key for where. Valid keys are #{ATTRIBUTES.keys}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    @data = Kaminari.paginate_array(InputFile.where(search_params)).page(params[:page]).per(10)
  end

  def max
    @max = InputFile.max(params[:attribute])
  end

  private

  def search_params
    {
      username: params[:username],
      inbox: params[:inbox],
      size: params[:size]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data/index.html.erb
<div class="page-header">
  <h3>Listagem</h3>
</div>

<%= form_tag(index_path, method: :get) do %>
  <fieldset>
    <div class='col-lg-3'>
      <div class="form-group">
        <%= text_field_tag :username, params[:username], placeholder: 'Username', class: 'form-control' %>
        <span class="help-block">Entre com o username</span>
      </div>
    </div>
    <div class='col-lg-3'>
      <div class="form-group">
        <%= text_field_tag :inbox, params[:inbox], placeholder: 'Inbox', class: 'form-control' %>
        <span class="help-block">Entre com o valor para inbox</span>
      </div>
    </div>
    <div class='col-lg-3'>
      <div class="form-group">
        <%= text_field_tag :size, params[:inbox], placeholder: 'Size', class: 'form-control' %>
        <span class="help-block">Entre com o valor para size</span>
      </div>
    </div>
    <div class='col-lg-3'>
      <div class="form-group">
        <%= submit_tag 'Filtrar', class: 'btn' %>
      </div>
    </div>
  </fieldset>
<% end %>

<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Inbox</th>
      <th>Size</th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do |value| %>
      <tr>
        <td><%= value[InputFile.attributes[:username]] %></td>
        <td><%= value[InputFile.attributes[:inbox]] %></td>
        <td><%= value[InputFile.attributes[:size]] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='text-center'>
  <%= paginate @data %>
</div>

app/views/data/max.html.erb
<div class="page-header">
  <h3>Valor máximo</h3>
</div>

<%= form_tag(max_path, method: :get) do %>
  <fieldset>
    <div class='col-lg-4'>
      <div class="form-group">
        <%= select_tag :attribute, options_for_select(InputFile.attributes.keys, params[:attribute]), class: 'form-control' %>
        <span class="help-block">Escolha um atributo para ver o maior valor</span>
      </div>
    </div>
    <div class='col-lg-3'>
      <%= submit_tag 'Buscar', class: 'btn' %>
    </div>
  </fieldset>
<% end %>

<hr>

<% if params[:attribute].present? %>
  <p>A linha que contém o maior valor para <%= params[:attribute] %> é:</p>
  <br>
  <dl>
    <dt>Username</dt>
    <dd><%= @max[InputFile.attributes[:username]] %></dd>
    <br>
    <dt>Inbox</dt>
    <dd><%= @max[InputFile.attributes[:inbox]] %></dd>
    <br>
    <dt>Size</dt>
    <dd><%= @max[InputFile.attributes[:size]] %></dd>
  </dl>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uol" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          <%= image_tag 'logo-uol.png', size: '82x30' %>
        </a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Listagem", index_path %></li>
            <li><%= link_to "Máximo", max_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>